/**
 * hud-styles — shared inline-style dictionary for HUD sub-components.
 *
 * Dark command-center aesthetic. Referenced as `styles.xxx` by nearly
 * every HUD presentational component and by the HUD composition root.
 */
import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  container: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    fontFamily: "'JetBrains Mono', 'Fira Code', 'Cascadia Code', monospace",
    color: "#8888aa",
    fontSize: "11px",
    zIndex: 10,
  },
  topLeft: {
    position: "absolute",
    top: 16,
    left: 16,
  },
  title: {
    fontSize: "14px",
    fontWeight: 700,
    color: "#aaaacc",
    letterSpacing: "0.1em",
    marginBottom: 4,
  },
  titleMark: {
    color: "#4a6aff",
    marginRight: 4,
  },
  subtitle: {
    fontSize: "10px",
    color: "#555577",
    letterSpacing: "0.05em",
  },
  topRight: {
    position: "absolute",
    top: 16,
    right: 16,
    textAlign: "right",
    pointerEvents: "auto",
  },
  sectionLabel: {
    fontSize: "9px",
    fontWeight: 700,
    color: "#555577",
    letterSpacing: "0.12em",
    marginBottom: 6,
  },
  presetRow: {
    display: "flex",
    gap: 4,
    flexWrap: "wrap",
    justifyContent: "flex-end",
  },
  presetBtn: {
    padding: "4px 8px",
    fontSize: "9px",
    fontFamily: "inherit",
    background: "rgba(20, 20, 40, 0.7)",
    border: "1px solid #333355",
    borderRadius: 3,
    color: "#7777aa",
    cursor: "pointer",
    letterSpacing: "0.05em",
    transition: "all 0.15s ease",
    backdropFilter: "blur(4px)",
  },
  presetBtnActive: {
    background: "rgba(74, 106, 255, 0.2)",
    borderColor: "#4a6aff",
    color: "#aaccff",
  },
  bottomLeft: {
    position: "absolute",
    bottom: 16,
    left: 16,
  },
  legendGrid: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
    maxWidth: 320,
  },
  legendItem: {
    display: "flex",
    alignItems: "center",
    gap: 4,
  },
  legendDot: {
    display: "inline-block",
    width: 8,
    height: 8,
    borderRadius: 2,
  },
  legendText: {
    fontSize: "9px",
    textTransform: "uppercase" as const,
    letterSpacing: "0.06em",
  },
  bottomRight: {
    position: "absolute",
    bottom: 16,
    right: 16,
    textAlign: "right",
  },
  infoText: {
    fontSize: "10px",
    color: "#7777aa",
    marginBottom: 2,
  },
  infoTextDim: {
    fontSize: "9px",
    color: "#444466",
  },
  zoomBar: {
    position: "relative" as const,
    height: 6,
    background: "rgba(30, 30, 60, 0.8)",
    border: "1px solid #333355",
    borderRadius: 3,
    overflow: "hidden" as const,
  },
  zoomBarFill: {
    position: "absolute" as const,
    top: 0,
    left: 0,
    height: "100%",
    background: "linear-gradient(90deg, #4a6aff, #6a8aff)",
    borderRadius: 3,
    transition: "width 0.15s ease",
  },
  zoomLabel: {
    position: "absolute" as const,
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "7px",
    color: "#aaccff",
    fontWeight: 700,
    letterSpacing: "0.06em",
    lineHeight: 1,
  },
  detailPanel: {
    position: "absolute",
    right: 16,
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(10, 10, 20, 0.85)",
    border: "1px solid #333355",
    borderRadius: 6,
    padding: "12px 16px",
    backdropFilter: "blur(8px)",
    maxWidth: 280,
    pointerEvents: "auto",
  },
  agentDetailPanel: {
    position: "absolute",
    left: 16,
    top: "50%",
    transform: "translateY(-50%)",
    background: "rgba(10, 10, 20, 0.85)",
    border: "1px solid #333355",
    borderRadius: 6,
    padding: "12px 16px",
    backdropFilter: "blur(8px)",
    maxWidth: 280,
    pointerEvents: "auto",
  },
};
