#!/usr/bin/env python3
"""
Sync EVENT_TYPES from packages/protocol/src/event.ts → ensemble_allowed_events.py.

Run after adding new event types to event.ts:
    python scripts/sync_event_types.py

CI integration: add to build pipeline to ensure Python/TS stay in sync.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
EVENT_TS = REPO_ROOT / "packages" / "protocol" / "src" / "event.ts"
OUTPUT_PY = REPO_ROOT / "scripts" / "ensemble_allowed_events.py"


def extract_event_types(ts_path: Path) -> list[str]:
    """Parse EVENT_TYPES array from event.ts."""
    content = ts_path.read_text(encoding="utf-8")

    # Extract the EVENT_TYPES array content between [ and ] as const
    match = re.search(
        r"export\s+const\s+EVENT_TYPES\s*=\s*\[(.*?)\]\s*as\s+const",
        content,
        re.DOTALL,
    )
    if not match:
        raise ValueError(f"Could not find EVENT_TYPES array in {ts_path}")

    array_body = match.group(1)

    # Extract all quoted strings
    types = re.findall(r'"([^"]+)"', array_body)
    return sorted(set(types))


def extract_obsolete_aliases(ts_path: Path) -> dict[str, str]:
    """Parse OBSOLETE_ALIASES from event.ts."""
    content = ts_path.read_text(encoding="utf-8")

    match = re.search(
        r"export\s+const\s+OBSOLETE_ALIASES.*?=\s*\{(.*?)\};",
        content,
        re.DOTALL,
    )
    if not match:
        return {}

    body = match.group(1)
    aliases: dict[str, str] = {}
    for m in re.finditer(r'"([^"]+)"\s*:\s*"([^"]+)"', body):
        aliases[m.group(1)] = m.group(2)
    return aliases


def generate_python(event_types: list[str], aliases: dict[str, str]) -> str:
    """Generate ensemble_allowed_events.py content."""
    lines = [
        '"""',
        "Auto-generated by sync_event_types.py — do NOT edit manually.",
        f"Source: packages/protocol/src/event.ts ({len(event_types)} event types)",
        '"""',
        "",
        "from __future__ import annotations",
        "",
        "ALLOWED_EVENT_TYPES: frozenset[str] = frozenset([",
    ]

    for t in event_types:
        lines.append(f'    "{t}",')

    lines.append("])")
    lines.append("")
    lines.append("OBSOLETE_ALIASES: dict[str, str] = {")

    for old, new in sorted(aliases.items()):
        lines.append(f'    "{old}": "{new}",')

    lines.append("}")
    lines.append("")
    lines.append("")
    lines.append("def resolve_event_type(raw: str) -> str:")
    lines.append('    """Resolve a raw event type string, applying aliases if needed."""')
    lines.append("    if raw in ALLOWED_EVENT_TYPES:")
    lines.append("        return raw")
    lines.append("    resolved = OBSOLETE_ALIASES.get(raw)")
    lines.append("    if resolved is not None:")
    lines.append("        return resolved")
    lines.append(f'    raise ValueError(f"Unknown event type: {{raw}}")')
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    if not EVENT_TS.exists():
        print(f"ERROR: {EVENT_TS} not found", file=sys.stderr)
        return 1

    event_types = extract_event_types(EVENT_TS)
    aliases = extract_obsolete_aliases(EVENT_TS)

    print(f"Extracted {len(event_types)} event types, {len(aliases)} aliases")

    output = generate_python(event_types, aliases)
    OUTPUT_PY.write_text(output, encoding="utf-8")
    print(f"Written to {OUTPUT_PY}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
